#!/usr/bin/env python3
import sys
from pathlib import Path

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Preformatted
except Exception as exc:
    print(f"reportlab import failed: {exc}", file=sys.stderr)
    sys.exit(2)


def parse_markdown_sections(text: str):
    sections = []
    current_title = "Report"
    current_lines = []
    for line in text.splitlines():
        if line.startswith("# "):
            if current_lines:
                sections.append((current_title, "\n".join(current_lines).strip()))
            current_title = line[2:].strip()
            current_lines = []
            continue
        current_lines.append(line)
    if current_lines:
        sections.append((current_title, "\n".join(current_lines).strip()))
    return sections


def main():
    if len(sys.argv) != 3:
        print("usage: generate_report_pdf.py <input_markdown> <output_pdf>", file=sys.stderr)
        return 1

    input_md = Path(sys.argv[1])
    output_pdf = Path(sys.argv[2])
    if not input_md.exists():
        print(f"input markdown does not exist: {input_md}", file=sys.stderr)
        return 1

    text = input_md.read_text(encoding="utf-8")
    sections = parse_markdown_sections(text)

    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(str(output_pdf), pagesize=letter, title="Client Pentest Report")
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Client Pentest Report", styles["Title"]))
    story.append(Spacer(1, 16))
    story.append(Paragraph("Generated by ULMCode report_writer", styles["Italic"]))
    story.append(PageBreak())

    for index, (title, body) in enumerate(sections):
        story.append(Paragraph(title, styles["Heading1"]))
        story.append(Spacer(1, 8))
        if body:
            story.append(Preformatted(body, styles["Code"]))
        story.append(Spacer(1, 12))
        if index < len(sections) - 1:
            story.append(PageBreak())

    doc.build(story)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
